name: Gatsby Publish

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [publish-event]
  #schedule:
  #  - cron: 0 0 * * 0 # weekly

env:
  CXXFLAGS: "--std=c++14"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
